package ua.shpp.eqbot.stage;

public enum PositionRegistrationService {
    INPUT_SERVICE_NAME,
    INPUT_PICTURE,
    SUNDAY_WORKING_HOURS,
    MONDAY_WORKING_HOURS,
    TUESDAY_WORKING_HOURS,
    WEDNESDAY_WORKING_HOURS,
    THURSDAY_WORKING_HOURS,
    FRIDAY_WORKING_HOURS,
    SATURDAY_WORKING_HOURS,
    TIME_BETWEEN_CLIENTS,
    DONE
}
