package ua.shpp.eqbot.stage;

public enum PositionRegistrationService {
    INPUT_SERVICE_NAME,
    INPUT_PICTURE,
    START_WORK_IN_SUNDAY,
    END_WORK_IN_SUNDAY,
    START_WORK_IN_MONDAY,
    END_WORK_IN_MONDAY,
    START_WORK_IN_TUESDAY,
    END_WORK_IN_TUESDAY,
    START_WORK_IN_WEDNESDAY,
    END_WORK_IN_WEDNESDAY,
    START_WORK_IN_THURSDAY,
    END_WORK_IN_THURSDAY,
    START_WORK_IN_FRIDAY,
    END_WORK_IN_FRIDAY,
    START_WORK_IN_SATURDAY,
    END_WORK_IN_SATURDAY,
    TIME_BETWEEN_CLIENTS,
    DONE
    }
