package ua.shpp.eqbot.stage;

public enum PositionMenu {
    MENU_START,
    MENU_CREATE_SERVICE,
    SEARCH_BY_CITY_NAME,
    SEARCH_BY_ID,
    SEARCH_USES_NAME_SERVICE,
    REGISTRATION_PROVIDER,
    REGISTRATION_SERVICE,
    REGISTRATION_FOR_THE_SERVICES_START,
    REGISTRATION_FOR_THE_SERVICES_DATE,
    REGISTRATION_FOR_THE_SERVICES_TIME,
    FEEDBACK,
    ADD_USERNAME_CUSTOMER,
    ADD_PHONE_CUSTOMER,
    DONE,
    BLACKLIST_ADD,
    BLACKLIST_DELETE
}
